// flow-typed signature: a15fd951e9e884788f737b6665480bd1
// flow-typed version: <<STUB>>/relay-subscriptions_v^1.0.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relay-subscriptions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'relay-subscriptions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relay-subscriptions/lib/createContainer' {
  declare module.exports: any;
}

declare module 'relay-subscriptions/lib/createSubscriptionQuery' {
  declare module.exports: any;
}

declare module 'relay-subscriptions/lib/Environment' {
  declare module.exports: any;
}

declare module 'relay-subscriptions/lib/index' {
  declare module.exports: any;
}

declare module 'relay-subscriptions/lib/Subscription' {
  declare module.exports: any;
}

declare module 'relay-subscriptions/lib/SubscriptionRequest' {
  declare module.exports: any;
}

declare module 'relay-subscriptions/lib/types' {
  declare module.exports: any;
}

declare module 'relay-subscriptions/lib/updateStoreData' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relay-subscriptions/lib/createContainer.js' {
  declare module.exports: $Exports<'relay-subscriptions/lib/createContainer'>;
}
declare module 'relay-subscriptions/lib/createSubscriptionQuery.js' {
  declare module.exports: $Exports<'relay-subscriptions/lib/createSubscriptionQuery'>;
}
declare module 'relay-subscriptions/lib/Environment.js' {
  declare module.exports: $Exports<'relay-subscriptions/lib/Environment'>;
}
declare module 'relay-subscriptions/lib/index.js' {
  declare module.exports: $Exports<'relay-subscriptions/lib/index'>;
}
declare module 'relay-subscriptions/lib/Subscription.js' {
  declare module.exports: $Exports<'relay-subscriptions/lib/Subscription'>;
}
declare module 'relay-subscriptions/lib/SubscriptionRequest.js' {
  declare module.exports: $Exports<'relay-subscriptions/lib/SubscriptionRequest'>;
}
declare module 'relay-subscriptions/lib/types.js' {
  declare module.exports: $Exports<'relay-subscriptions/lib/types'>;
}
declare module 'relay-subscriptions/lib/updateStoreData.js' {
  declare module.exports: $Exports<'relay-subscriptions/lib/updateStoreData'>;
}
